[package]
name = "dat-network-protocol"
description = "Dat Network Protocol protobuf definitions."
version = "0.1.1"
authors = ["Yoshua Wuyts <yoshuawuyts@gmail.com>"]
license = "MIT OR Apache0.0"

[dependencies]
protobuf = "1.4.3"

[build-dependencies]
protoc-rust = "1.4"
