[package]
name = "sleep-protocol"
description = "SLEEP Network Protocol protobuf definitions."
version = "0.1.0"
authors = ["Yoshua Wuyts <yoshuawuyts@gmail.com>"]
license = "Apache-2.0"

[dependencies]
protobuf = "1.4.3"

[build-dependencies]
protoc-rust = "1.4"
